version: 2
project_name: "kubectl-reap"

release:
  github:
    owner: "guppy0130"
    name: "kubectl-reap"

builds:
  - id: "kubectl-reap"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "amd64"
      - "arm64"
    goarm:
      - "7"
    env:
      - CGOENABLED=0
      - GO111MODULE=on
    main: ./cmd/kubectl-reap/main.go
    ldflags:
      - -s -w
      - -X github.com/guppy0130/kubectl-reap/pkg/version.Version={{.Tag}}
      - -X github.com/guppy0130/kubectl-reap/pkg/version.Revision={{.ShortCommit}}

archives:
  - format: "tar.gz"
    id: "kubectl-reap"
    builds:
      - "kubectl-reap"

brews:
  - repository:
      owner: guppy0130
      name: kubectl-reap
    homepage: https://github.com/guppy0130/kubectl-reap
    description: kubectl plugin that deletes unused Kubernetes resources
    directory: Formula

krews:
  - name: "reap"
    short_description: kubectl plugin that deletes unused Kubernetes resources
    description: >-
      This plugin deletes unused Kubernetes resources. It supports Pods,
      ConfigMaps, Secrets, PersistentVolumes, PersistentVolumeClaims, Jobs,
      PodDisruptionBudgets, and HorizontalPodAutoscalers.
    homepage: https://github.com/guppy0130/kubectl-reap
    repository:
      owner: guppy0130
      name: kubectl-reap
