# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlReap < Formula
  desc "kubectl plugin that deletes unused Kubernetes resources"
  homepage "https://github.com/guppy0130/kubectl-reap"
  version "0.12.0"

  on_macos do
    on_intel do
      url "https://github.com/guppy0130/kubectl-reap/releases/download/v0.12.0/kubectl-reap_0.12.0_darwin_amd64.tar.gz"
      sha256 "e3b55e763e51d014d706eae2ce8e5906f2a31e97f2e298994633922bf9f5ce5e"

      def install
        bin.install "kubectl-reap"
      end
    end
    on_arm do
      url "https://github.com/guppy0130/kubectl-reap/releases/download/v0.12.0/kubectl-reap_0.12.0_darwin_arm64.tar.gz"
      sha256 "9487d4fe58b833279441deff49338063d7b16af270e0b52709001f8e114a51ad"

      def install
        bin.install "kubectl-reap"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/guppy0130/kubectl-reap/releases/download/v0.12.0/kubectl-reap_0.12.0_linux_amd64.tar.gz"
        sha256 "70205717b29299f393a5df797a4f7a7433ad7d926a4563c5dc42976abfee4879"

        def install
          bin.install "kubectl-reap"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/guppy0130/kubectl-reap/releases/download/v0.12.0/kubectl-reap_0.12.0_linux_arm64.tar.gz"
        sha256 "a352620894ced15429bd0a9cddb3c3ec798082ace124e40908504636cacc6a11"

        def install
          bin.install "kubectl-reap"
        end
      end
    end
  end
end
