name: Lint

on:
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-golangci-lint@v2
